// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCollection(arg1:string,arg2:string):Promise<Array<main.SmartCollection>>;

export function GetCollectionRequest(arg1:string,arg2:string):Promise<main.Request>;

export function GetCollections():Promise<Array<main.SmartCollection>>;

export function Run(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<main.Header>):Promise<main.Result>;

export function SaveToCollection(arg1:main.Request):Promise<Array<main.SmartCollection>>;
